### ISSUE TITLE
Incompatability with Lua 5.3 functions

### ISSUE THREAD

**Issue by james-callahan** [Mashape/lua-pack#1]
lua_pack's modification of the string library conflicts with the lua 5.3 functions string.pack and [string.unpack](https://www.lua.org/manual/5.3/manual.html#pdf-string.unpack).
This breaks feature detection as used by some cross-lua-version compatible libraries.

Could lua_pack be modified to return its own table of functions so that it doesn't conflict?

**Comment by h824612113** [comment]
Hello,how can I use this 'lua-pack' at lua5.1?

**Comment by Xottab-DUTY** [comment]
This issue is solved in #3

**Comment by Tieske** [comment]
thx @Xottab-DUTY , closing this.
