### ISSUE TITLE
Unable to install lua_pack v1.0.5 using git protocol

### ISSUE THREAD

**Issue by chirag-manwani** [Mashape/lua-pack#4]
Hi, I am currently using Kong 2.2.0 in production which depends on lua_pack v1.0.5
The [luarocks package](https://luarocks.org/modules/kong/lua_pack/1.0.5-0) for lua_pack v1.0.5 only has a [rockspec](https://luarocks.org/manifests/kong/lua_pack-1.0.5-0.rockspec) and **no rock (src)** to install the package, so luarocks clones the repo and then installs the package.
Now the issue is that the URL("git://github.com/mashape/lua-pack") in the rockspec uses the **git** protocol, the support for which has been disabled from today from Github, refer [this](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git).

If anyone tries to install lua_pack v.1.0.5, they will get this error-
```
$ luarocks install lua_pack 1.0.5

Warning: Failed searching manifest: Failed downloading https://luarocks.org - Failed downloading https://luarocks.org/manifest-5.1 - /root/.cache/luarocks/https___luarocks.org/manifest-5.1
Warning: Failed searching manifest: Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest-5.1 - /root/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest-5.1
Warning: falling back to curl - install luasec to get native HTTPS support
Installing http://luafr.org/moonrocks/lua_pack-1.0.5-0.rockspec
Cloning into 'lua-pack'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Error: Failed cloning git repository.
```
Since lua_pack v.1.0.5 is a dependency for Kong for versions up to 2.6.0, installation for kong using luarocks will fail with the same error. 

Possible Fix-

If the corresponding rock file is uploaded to luarocks, then the package can be installed using it and there would be no need to clone the git repo. This is how it is still possible to install v2.0.0 without any issues. (Since it has both a rockspec file and a rock file https://luarocks.org/modules/kong/lua_pack/2.0.0-0).

**Comment by Tieske** [comment]
uploaded, please try again.
